server:
  port: 8010
  servlet:
    context-path: /springbootdemo

offcn_ip:
  1.1.1.1
offcn_port:
  9999

userbody:
  name:
    "\u4f18\u5c31\u4e1a"
  password:
    123456
  birthday:
    1992.10.28
  mobile:
    13802789765
  address:
    "\u5317\u4eac\u5e02\u671d\u9633\u533a"
spring:
  profiles:
    active: dev